project_name: autoapps

env:
  - GO111MODULE=on

env_files:
  github_token: .github_token

before:
  hooks:
    - go mod tidy

builds:
  - binary: autoapps
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64

archives:
  - format: binary

release:
  github:
    owner: joshrwolf
    name: autoapps
  name_template: "Version {{.Version}}"